s = ''
s = s .. 'HTTP/1.0 200 OK\n\n'
s = s .. '<html>'
s = s .. '<head>'
s = s .. '<title>Control LED through WiFi</title>'
s = s .. '<meta charset="utf-8">'
s = s .. '<meta http-equiv="X-UA-Compatible" content="IE=edge">'
s = s .. '<meta name="viewport" content="width=device-width, initial-scale=1">'
s = s .. '<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>'
s = s .. '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">'
s = s .. '</head>'
s = s .. '<body>'
s = s .. '<div class="container">'
s = s .. '<h1>MY LED</h1>'
s = s .. '<h2>Control LED Using Cell Phone</h2>'
s = s .. '<div class="row">'
s = s .. '<div class="col-md-2">'
s = s .. '<a href="?pin=ON" class="btn btn-block btn-lg btn-success" role="button">Switch ON LED</a>'
s = s .. '</div>'
s = s .. '<div class="col-md-2">'
s = s .. '<a href="?pin=OFF" class="btn btn-block btn-lg btn-danger" role="button">Switch OFF LED</a>'
s = s .. '</div>'
s = s .. '</div>'
s = s .. '</body>'
s = s .. '</html>'
